name: PR Build (preview)

on:
  pull_request:
    branches: [main]

jobs:
  pr-build:
    uses: operation-grimoire/extensions-ci/.github/workflows/pr-build.yml@v1
    secrets: inherit
    permissions:
      contents: write
      packages: read
      pull-requests: write
