name: PR Build (dry-run)

on:
  pull_request:
    branches: [main]

jobs:
  pr-build:
    uses: operation-grimoire/extensions-ci/.github/workflows/pr-build.yml@v1
    secrets: inherit
    permissions:
      contents: read
      packages: read
