name: PR preview cleanup

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  pr-cleanup:
    uses: operation-grimoire/extensions-ci/.github/workflows/pr-cleanup.yml@v1
    secrets: inherit
    permissions:
      contents: write
